services:
  - type: web
    name: telegram-anitoon-s1-bot
    runtime: python
    plan: free
    region: singapore
    branch: main

    buildCommand: pip install -r requirements.txt

    startCommand: python main.py

    healthCheckPath: /health

    autoDeploy: true
